### ISSUE TITLE
保存二维码提示保存失败

### ISSUE THREAD

**Issue by AI-Cloud** [PureDark/H-Viewer#32]
保存二维码提示保存失败
手机：MX4 Pro
Android版本：5.1.1
出错日志：
```
java.io.FileNotFoundException: content:/com.android.externalstorage.documents/tree/primary%3AH-Viewer%2Fdownload/QrCodes/Pixiv.jpg: open failed: ENOENT (No such file or directory)
	at libcore.io.IoBridge.open(IoBridge.java:456)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:87)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:72)
	at ml.puredark.hviewer.utils.ImageScaleUtil.saveToFile(ImageScaleUtil.java:102)
	at ml.puredark.hviewer.ui.activities.ModifySiteActivity.saveQrCode(ModifySiteActivity.java:213)
```

**Comment by PureDark** [comment]
感谢反馈，下个版本修复
从File操作转换成使用Document进行文件操作、以前写的地方不记得改了

**Comment by PureDark** [comment]
已修复
